apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  ports:
    - port: {{ .Values.postgres.ports.main }}
      nodePort: {{ .Values.global.nodePorts.postgres }}
  selector:
    app: postgres
