apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: {{ .Values.postgres.ports.main }}
      {{- if and .Values.postgres.nodePorts .Values.postgres.nodePorts.main }}
      nodePort: {{ tpl .Values.postgres.nodePorts.main . }}
      {{- end }}
