apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: {{ .Release.Name }}
spec:
  replicas: 1
  serviceName: postgres
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      annotations:
        helm.sh/revision: "{{ .Release.Revision }}"
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: postgres:15.3
          args: [ -c, config_file=/etc/postgresql/postgresql.conf ]
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - name: postgres-port
              containerPort: 5432
          volumeMounts:
            - name: data-volume
              mountPath: /var/lib/postgresql/data/
            - name: configs
              mountPath: /etc/postgresql/
            - name: tls
              mountPath: /tls/
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: configs
          configMap:
            name: postgres-configs
            items:
              - key: postgresql.conf
                path: postgresql.conf
        - name: tls
          secret:
            secretName: tls-secret
            defaultMode: 0400
