apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
spec:
  replicas: {{ .Values.postgres.replicas }}
  serviceName: postgres
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      annotations:
        helm.sh/revision: "{{ .Release.Revision }}"
    spec:
      securityContext:
        fsGroup: 999
      volumes:
        - name: configs
          configMap:
            name: postgres-configs
            defaultMode: 0400
        - name: tls
          secret:
            secretName: tls-secret
            defaultMode: 0400
        - name: data-volume
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          args: [ -c, config_file=/etc/postgresql/postgresql.conf ]
          env:
            {{- range $name, $value := .Values.postgres.envs }}
            - name: {{ $name }}
              value: {{ $value }}
            {{- end }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          envFrom:
            - secretRef:
                name: postgres-secrets
          ports:
            {{- range $name, $port := .Values.postgres.ports }}
            - name: {{ $name }}
              containerPort: {{ $port }}
            {{- end }}
          volumeMounts:
            {{- range $path := .Values.postgres.configs | keys }}
            - name: configs
              mountPath: {{ $path }}
              subPath: {{ $path }}
            {{- end }}
            - name: tls
              mountPath: /tls/
            - name: data-volume
              mountPath: /var/lib/postgresql/data/
