apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: sealed-secrets
      repoURL: https://bitnami-labs.github.io/sealed-secrets
      targetRevision: 2.13.0
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
      - CreateNamespace=true
      - PruneLast=true
