apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-postgres-pv
  namespace: dev
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: do-block-storage-xfs-retain
  csi:
    driver: dobs.csi.digitalocean.com
    volumeHandle: 062f374a-50a8-11ee-b32a-0a58ac120c8b
    fsType: xfs

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: do-block-storage-xfs-retain
  volumeName: dev-postgres-pv
