apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tmp-sts
spec:
  selector:
    matchLabels:
      app: tmp
  replicas: 1
  template:
    metadata:
      labels:
        app: tmp
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: postgres:15.3
          env:
            - name: POSTGRES_PASSWORD
              value: password
  serviceName: postgres
