apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: ingress-nginx
      helm:
        valueFiles:
          - $values/environments/ingress-nginx/values.yaml
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.7.2
    - ref: values
      repoURL: https://github.com/Creaty-Co/creaty-chart
      targetRevision: envy
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
      - CreateNamespace=true
      - PruneLast=true
