apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbeat-deployment
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ tpl (toString .Values.api.cbeat.replicas) . }}
  selector:
    matchLabels:
      app: cbeat
  template:
    metadata:
      labels:
        app: cbeat
    spec:
      initContainers:
        {{- include "init-wait-for-redis" (dict "redis_host" "redis-celery") | indent 8 }}
        {{- include "init-wait-for-postgres" (dict "postgres_host" "postgres") | indent 8 }}
      containers:
        - name: cbeat
          image: {{ include "api_image" . }}
          command: [celery, -A, api, beat, -S, django, -l, info]
          env: {{- include "env" (dict "_" $ "_envs" .Values.api.envs) | indent 12 }}
          resources: {{- toYaml .Values.api.cbeat.resources | nindent 12 }}
