apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbeat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cbeat
  template:
    metadata:
      labels:
        app: cbeat
      annotations:
        helm.sh/revision: "{{ .Release.Revision }}"
    spec:
      initContainers:
        {{- include "init-wait-for-redis" (dict "redis_host" "redis-celery") | indent 8 }}
        {{- include "init-wait-for-postgres" (dict "postgres_host" "postgres") | indent 8 }}
      containers:
        - name: cbeat
          image: {{ include "api_image" . }}
          command: [ celery, -A, api, beat, -S, django, -l, info ]
          env: {{- include "env" (dict "_" $ "_envs" .Values.api.envs) | indent 12 }}
          resources: {{- toYaml .Values.api.cbeat.resources | nindent 12 }}
