apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-deployment
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ tpl (toString .Values.api.celery.replicas) . }}
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      initContainers:
        {{- include "init-wait-for-redis" (dict "redis_host" "redis-celery") | indent 8 }}
      containers:
        - name: celery
          image: {{ include "api_image" . }}
          command: [celery, -A, api, worker, -c, "2", -P, gevent, -l, info]
          env: {{- include "env" (dict "_" $ "_envs" .Values.api.envs) | indent 12 }}
          resources: {{- toYaml .Values.api.celery.resources | nindent 12 }}
