apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
      annotations:
        helm.sh/revision: "{{ .Release.Revision }}"
    spec:
      containers:
        - name: celery
          {{- tpl (.Files.Get "files/api.yml") . | nindent 10 }}
          command: [ celery, -A, api, worker, -c, "2", -P, gevent, -l, info ]
