apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      annotations:
        helm.sh/revision: "{{ .Release.Revision }}"
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          {{- tpl (.Files.Get "files/api.yml") . | nindent 10 -}}
          command: [ gunicorn, api.wsgi, -c, gunicorn/config.py ]
          ports:
            - name: api-port
              containerPort: 8000
          resources:
            limits:
              memory: 250Mi
