apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # gzip
      gzip on;
      gzip_disable "msie6";
      gzip_vary on;
      gzip_proxied any;
      gzip_comp_level 6;
      gzip_buffers 16 8K;
      gzip_http_version 1.1;
      gzip_min_length 256;
      gzip_types *;
    nginx.ingress.kubernetes.io/limit-rps: '2'
spec:
  ingressClassName: nginx
  rules:
    - host: {{ include "api_domain" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80
    - host: {{ include "web_domain" . }}
      http:
        paths:
          - path: /platform/token
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80
    - host: {{ include "api_domain" . }}
      http:
        paths:
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: api-ws
                port:
                  number: 80
