apiVersion: v1
kind: Service
metadata:
  name: platform-postgres
spec:
  type: NodePort
  selector:
    app: platform-postgres
  ports:
    - port: {{ .Values.platform_postgres.ports.main }}
      {{- if and .Values.postgres.nodePorts .Values.platform_postgres.nodePorts.main }}
      nodePort: {{ tpl .Values.platform_postgres.nodePorts.main . }}
      {{- end }}
