apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: envy
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://github.com/Creaty-Co/creaty-chart
    targetRevision: envy
    helm:
      valueFiles:
        - environments/envy/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 3
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
