apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: {{ .Release.Revision }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        helm.sh/revision: "{{ .Release.Revision }}"
    spec:
      initContainers:
        - name: init-web
          image: ghcr.io/creaty-co/creaty-web/web:latest
          command: [ bash, -c ]
          args:
            - mv /web/* /web-dir
          volumeMounts:
            - name: web-dir
              mountPath: /web-dir/
        - name: init-api
          image: ghcr.io/creaty-co/creaty-api/api:latest
{{/*          command: [ python, manage.py ]*/}}
{{/*          args: [ collectstatic, --noinput ]*/}}
          command: [ env ]
          envFrom:
            - secretRef:
                name: postgres-secrets
            - secretRef:
                name: api-secrets
            - configMapRef:
                name: api-envs
          volumeMounts:
            - name: api-static-dir
              mountPath: /api/static/
      containers:
        - name: nginx
          image: nginx:1.25.2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: configs
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: web-dir
              mountPath: /etc/nginx/html/web/
            - name: api-static-dir
              mountPath: /etc/nginx/html/api/static/
      volumes:
        - name: configs
          configMap:
            name: nginx-configs
        - name: web-dir
          emptyDir: {}
        - name: api-static-dir
          emptyDir: {}
