apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        helm.sh/revision: "{{ .Release.Revision }}"
    spec:
      volumes:
        - name: configs
          configMap:
            name: nginx-configs
        - name: web-dir
          emptyDir: {}
        - name: api-static-dir
          emptyDir: {}
      initContainers:
        - name: init-web
          image: ghcr.io/creaty-co/creaty-web/web:latest
          command: [ bash, -c, mv /web/* /web-dir ]
          volumeMounts:
            - name: web-dir
              mountPath: /web-dir/
        - name: init-api
          {{- tpl (.Files.Get "files/api.yml") . | nindent 10 -}}
          command: [ python, manage.py, collectstatic, --noinput ]
          volumeMounts:
            - name: api-static-dir
              mountPath: /api/static/
      containers:
        - name: nginx
          image: nginx:1.25.2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: configs
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: web-dir
              mountPath: /etc/nginx/html/web/
            - name: api-static-dir
              mountPath: /etc/nginx/html/api/static/
