apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-celery-deployment
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ tpl (toString .Values.redis.celery.replicas) . }}
  selector:
    matchLabels:
      app: redis-celery
  template:
    metadata:
      labels:
        app: redis-celery
    spec:
      volumes:
        - name: configs
          configMap:
            name: redis-celery-configs
      containers:
        - name: redis-celery
          image: {{ .Values.redis.image }}
          ports: {{- include "ports" .Values.redis.ports | indent 12 }}
          volumeMounts: {{- include "configs" .Values.redis.celery.configs | indent 12 }}
          resources: {{- toYaml .Values.redis.celery.resources | nindent 12 }}
          livenessProbe: {{- tpl (toYaml .Values.redis.probe) . | nindent 12 }}
          readinessProbe: {{- tpl (toYaml .Values.redis.probe) . | nindent 12 }}
