apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        configmapHash: {{
          include (print $.Template.BasePath "/nginx/configmap.yaml") . | sha256sum
        }}
    spec:
      initContainers:
        - name: init-web
          image: ghcr.io/creaty-co/creaty-web/web:latest
          command: [ bash, -c ]
          args:
            - mv /web/* /web-dir
          volumeMounts:
            - name: web-dir
              mountPath: /web-dir/
        - name: init-api
          image: ghcr.io/creaty-co/creaty-api/api:latest
          command: [ python, manage.py ]
          args:
            - collectstatic
            - --noinput
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          envFrom:
            - configMapRef:
                name: api-configmap
          volumeMounts:
            - name: api-static-dir
              mountPath: /api/static/
      containers:
        - name: nginx
          image: nginx:1.25.2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-main
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: web-dir
              mountPath: /etc/nginx/html/web/
            - name: api-static-dir
              mountPath: /etc/nginx/html/api/static/
      volumes:
        - name: nginx-config-main
          configMap:
            name: nginx-configmap
        - name: web-dir
          emptyDir: {}
        - name: api-static-dir
          emptyDir: {}
