apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        configmapHash: {{
          include (print $.Template.BasePath "/nginx/configmap.yaml") . | sha256sum
        }}
    spec:
      initContainers:
        - name: init-web
          image: ghcr.io/creaty-co/creaty-web/web:latest
          command: [ cp ]
          args: [ -r, /web/, /web-dir/ ]
          volumeMounts:
            - name: web-dir
              mountPath: /web-dir/
      containers:
        - name: nginx
          image: nginx:1.25.2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/
            - name: web-dir
              mountPath: /etc/nginx/html/web/
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-configmap
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: web-dir
          emptyDir: {}
