apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: {{ .Release.Name }}

spec:
  ingressClassName: nginx
  rules:
    - host: {{ template "web_domain" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
