apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: {{ .Release.Name }}
spec:
  replicas: 1
  serviceName: postgres
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      annotations:
        configmapHash: {{
          include (print $.Template.BasePath "/postgres/configmap.yaml") . | sha256sum
        }}
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: postgres:15.3
          args: [ "-c", "config_file=/etc/postgresql/postgresql.conf" ]
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - name: postgres-port
              containerPort: 5432
          volumeMounts:
            - name: postgres-data-volume
              mountPath: /var/lib/postgresql/data/
            - name: postgres-config
              mountPath: /etc/postgresql/
            - name: postgres-tls
              mountPath: /tls/
      volumes:
        - name: postgres-data-volume
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: postgres-config
          configMap:
            name: postgres-configmap
            defaultMode: 0400
            items:
              - key: postgresql.conf
                path: postgresql.conf
        - name: postgres-tls
          secret:
            secretName: tls-secret
            defaultMode: 0400
