{{- range $secretType, $secrets := .Values.secrets }}
{{- range $secretName, $secretData := $secrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $secretName }}
spec:
  encryptedData:
    {{- range $key, $value := $secretData }}
    {{ $key }}: {{ $value }}
    {{- end }}
  template:
    metadata:
      name: {{ $secretName }}
    type: {{ $secretType }}
{{- end }}
{{- end }}
