apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secrets
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAkw4ShlDs3UQRsbVd42HnzRP/xCcONmbexH6Kc+1ucZD5IXfMQp1iIkg+6PwqjBUDUzTwZb5204pHaM+AmnnlZCej3mIhujU4tBrJ0u/nb/+6nbql5q47ENI5abla3awPjdeQWnujewqecOJcIMgP/z+H6YaJrjLZrrbiPSUJ5V4bpfLfiOU0nBR1aO4OSACv9hmGW6C1g4o1Nl0guUBB4WgAUKPxE58MXkSjOk0uxwF2CMIRGbKSZNGuAy/pnzFP9ccMG9SmA1OVjsJ2iuIzehPqycgYKpo3ii2CiN6IbAHU8TyAtKfhLuqpshli39dWcqGMlhgOIw3EuoXyI/Y4OKSuRB9oCiRM9W7VwqmkGjQ5WKOvbQ3h+oDaxoLJFwLAI5+rWZcGWHJNMLSQAVSWZ6LXsE+8EgkKNHOHdWbmlj2yNOlmXfDw0Dur+rV0x52aNLbhaPqsFVeD7FEe/BKQf5CtRD6Gm/dkq1uxN3VinsL4T7IitwHmvS1oKynTDbUzJRvrPUJouQ6yT8y47rnh/qqP8Tqtje6H8EFoRkj8rhzRZ16CSNSWG3i1JNIwk3ZCR9kqvtQVAdkaAkeAouBGy/YvBhg/+2sfUoSjK641aP9djG2L3oXRbBfkiM6tlNRccC5lov0DzHefYNEkFCpCRbMKe2KpSZ5A4ofvGR+Rs8SdT1Wu8yO+AnQTAl8/hNwiDCuyRayWjvA==
  template:
    metadata:
      name: postgres-secrets
    type: Opaque
