apiVersion: apps/v1
kind: Deployment
metadata:
  name: cal-api-deployment
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.cal.api.replicas }}
  selector:
    matchLabels:
      app: cal-api
  template:
    metadata:
      labels:
        app: cal-api
    spec:
      initContainers:
        {{- include "init-wait-for-postgres" (dict "postgres_host" "cal-postgres") | indent 8 }}
      containers:
        - name: cal-api
          image: {{ .Values.cal.image }}
          env: {{- include "env" (dict "_" $ "_envs" (merge .Values.cal.envs .Values.cal.api.envs)) | indent 12 }}
          ports: {{- include "ports" .Values.cal.ports | indent 12 }}
          resources: {{- toYaml .Values.cal.api.resources | nindent 12 }}
