apiVersion: apps/v1
kind: Deployment
metadata:
  name: cal-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cal-api
  template:
    metadata:
      labels:
        app: cal-api
      annotations:
        helm.sh/revision: "{{ .Release.Revision }}"
    spec:
      containers:
        - name: cal-api
          image: {{ .Values.cal.image }}
          env: {{- include "env" (dict "_" $ "_envs" (merge .Values.cal.envs .Values.cal.api.envs)) | indent 12 }}
          ports: {{- include "ports" .Values.cal.ports | indent 12 }}
          resources: {{- toYaml .Values.cal.api.resources | nindent 12 }}
