apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: {{ .Values.api.image }}
          command: [ python, manage.py, migrate ]
          env: {{- include "env" (dict "_" $ "_envs" .Values.api.envs) | indent 12 }}
      restartPolicy: Never
