apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    annotations:
      helm.sh/revision: {{ .Release.Revision }}
    spec:
      containers:
        - name: redis
          image: redis:7.2.1
          ports:
            - name: redis-port
              containerPort: 6379
          volumeMounts:
            - name: configs
              mountPath: /usr/local/etc/redis/
      volumes:
        - name: configs
          configMap:
            name: redis-configs
            items:
              - key: redis.conf
                path: redis.conf
