apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
      annotations:
        helm.sh/revision: "{{ .Release.Revision }}"
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            {{- range $name, $port := .Values.redis.ports }}
            - name: {{ $name }}
              containerPort: {{ $port }}
            {{- end }}
          volumeMounts:
            {{- range $config := .Values.redis.configs }}
            - name: configs
              mountPath: {{ $config.path }}
              subPath: {{ $config.name }}
            {{- end }}
      volumes:
        - name: configs
          configMap:
            name: redis-configs
