apiVersion: v1
kind: Service
metadata:
  name: cal-postgres
spec:
  type: NodePort
  selector:
    app: cal-postgres
  ports:
    - port: {{ .Values.cal_postgres.ports.main }}
      {{- if and .Values.postgres.nodePorts .Values.cal_postgres.nodePorts.main }}
      nodePort: {{ tpl .Values.cal_postgres.nodePorts.main . }}
      {{- end }}
