apiVersion: v1
kind: Service
metadata:
  name: cal-postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: cal-postgres-port
      nodePort: 30001
  selector:
    app: cal-postgres
