apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: global-cal-secrets
  annotations:
    avp.kubernetes.io/path: /kv/data/environments/$ARGOCD_ENV_ENVIRONMENT/platform
stringData:
  CALENDSO_ENCRYPTION_KEY: <CALENDSO_ENCRYPTION_KEY>
  NEXTAUTH_SECRET: <NEXTAUTH_SECRET>
