{{/*apiVersion: v1*/}}
{{/*kind: Service*/}}
{{/*metadata:*/}}
{{/*  name: api*/}}
{{/*  namespace: {{ .Release.Name }}*/}}
{{/*spec:*/}}
{{/*  selector:*/}}
{{/*    app: api*/}}
{{/*  ports:*/}}
{{/*    - protocol: TCP*/}}
{{/*      port: 80*/}}
{{/*      targetPort: api-port*/}}
