apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: api-secrets
  annotations:
    avp.kubernetes.io/path: /kv/data/environments/$ARGOCD_ENV_ENVIRONMENT/api
stringData:
  SECRET_KEY: <SECRET_KEY>
