apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cal-postgres-secrets
  annotations:
    avp.kubernetes.io/path: /kv/data/environments/$ARGOCD_ENV_ENVIRONMENT/platform-postgres
stringData:
  POSTGRES_PASSWORD: <POSTGRES_PASSWORD>
