apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-secrets
  annotations:
    avp.kubernetes.io/path: /kv/data/environments/$ARGOCD_ENV_ENVIRONMENT/postgres
stringData:
  POSTGRES_PASSWORD: <POSTGRES_PASSWORD>
